name: freezed_hands_on
description: A hands on freezed.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
